version: '3'
# volumes:
#   mysql_db_ppd:
networks:
  root_network_app:
    external: true    
  # workflow_network_app:
  #   external: true


services:
  server-app-ppd:
    container_name: server-app-ppd
    build:
      context: .
      dockerfile: Dockerfile-ppd.dockerfile
    image: `${IMG_TAG}`
    restart: always
    volumes:
      - "/home/node/app:/home/node/app"
    # ports:
    #   - 127.0.0.1:8089:8089
    # expose:
    #   - 8089
    environment:
      APP_PORT: 8089
      APP_HOST: 0.0.0.0    
      DB_HOST: 109.123.254.17
      DB_PORT: 3307
      DB_USER: root
      DB_PWD: Dsp-archi-15
      DB_DATABASE: DSP5-ARCHI-DB-PPD
      FACEBOOK_CLIENT_ID: 834324708244777
      FACEBOOK_CLIENT_SECRET: b23338d8d100a9f261b7d3199fe7ef06
      FACEBOOK_CALLBACK_URL: http://thetiptop.recette.api.com/auth/facebook/callback
      GOOGLE_CLIENT_ID: 574508009757-dfq7soqtakor952logu1rup06r53hsjr.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_CALLBACK_URL: http://thetiptop.recette.api.com/auth/google/callback
      URL_REDIRECT_AUTH_SOCIAL_MEDIA: http://thetiptop.recette.api.com/social-media/
      BASE_URL_FRONT: http://thetiptop.recette.com
      BASE_URL: http://thetiptop.recette.api.com
      BASE_URL_FOR_AXIOS: http://127.0.0.1:8089
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: pre-prod
      SERVICE_NAME: nodeapp
    # depends_on:
    #   - mysqldb-ppd
    networks:
      # workflow_network_app:
      root_network_app:
    labels:
      - traefik.enable=true
      - traefik.http.routers.server-app-ppd.rule=Host(`thetiptop.recette.api.com`)
      - traefik.http.routers.server-app-ppd.middlewares=network-internet@docker
      - traefik.http.services.server-app-ppd.loadbalancer.server.port=8089

  # mysqldb-ppd:
  #   image: mysql:8.0
  #   container_name: mysqldb-ppd
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes:
  #     - "mysql_db_ppd:/var/lib/mysql"    
  #   ports:
  #     - 3307:3306
  #   expose:
  #     - 3307
  #   environment:
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: Dsp-archi-15
  #     MYSQL_DATABASE: DSP5-ARCHI-DB
  #     MYSQL_ROOT_PASSWORD: Dsp-archi-15
  #     SERVICE_TAGS: prod
  #     SERVICE_NAME: mysqldb-ppd
  #   networks:
  #     - thetiptop
  #   labels:
  #     - traefik.enable=false    
